### ISSUE TITLE
On es el pull request?

### ISSUE THREAD

**Issue by aseques** [OSM-Catalan/voicecat#1]
He estat buscant on era el pull request en el repositori de osmand per si podia fer un comentar o donar un cop de ma i no el veig enlloc, el podeu enllaçar aquí?

**Comment by yopaseopor** [comment]
Ja no el trobareu ,es va afegir originalment a Osmand i allà hi és quan
tries català en la app.
El pull request està tancat . El moment en afegir-los és aquest


https://github.com/osmandapp/OsmAnd-resources/commit/6617242d37b7936caba567b0be871e32e7433237#diff-d59e7aa4e9d059e49518421d0e37c5c4

Salut
yopaseopor

**Comment by aseques** [comment]
ok, perfecte, si ja està integrat, tot fantàstic.
